module.exports = {
	extends: [
		`plugin:promise/recommended`,
		`plugin:eslint-comments/recommended`,
		`plugin:unicorn/recommended`,
		`plugin:prettier/recommended`,
		`prettier/unicorn`,
	],
	plugins: [`unicorn`, `no-secrets`, `promise`, `eslint-comments`],
	rules: {
		"consistent-return": `off`,
		"import/first": `off`,
		"import/newline-after-import": `off`,
		"import/prefer-default-export": `off`,
		"import/no-anonymous-default-export": [
			`error`,
			{
				allowAnonymousClass: true,
				allowAnonymousFunction: true,
				allowArrowFunction: true,
			},
		],
		"no-bitwise": `off`,
		"no-console": `off`,
		"no-plusplus": `off`,
		"no-underscore-dangle": `off`,
		"no-use-before-define": `off`,
		"no-secrets/no-secrets": `error`,
		"prefer-const": `error`,
		"prefer-template": `error`,
		"quotes": [`error`, `backtick`],
		"radix": [`error`, `as-needed`],
		"unicorn/filename-case": `off`,
		"unicorn/no-nested-ternary": `off`,
		"unicorn/prevent-abbreviations": `off`,
		"eslint-comments/disable-enable-pair": `off`,
	},
};
